# fly.toml app configuration file generated for ysc-sandbox on 2025-11-14T08:35:48-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ysc-sandbox'
primary_region = 'sjc'
kill_signal = 'SIGTERM'

[build]

[deploy]
release_command = "/bin/sh -lc 'DATABASE_URL=${RAW_DATABASE_URL} /app/bin/migrate && /app/bin/seed'"

[env]
ENVIRONMENT = 'sandbox'
PHX_HOST = 'ysc-sandbox.fly.dev'
PORT = '4000'
ERL_AFLAGS = '-proto_dist inet6_tcp'
ECTO_IPV6 = 'true'
STRIPE_SINGLE_PRICE_ID = 'price_1SUZVAREiftrEncLCHpFzbJY'
STRIPE_FAMILY_PRICE_ID = 'price_1SUZVcREiftrEncLSSYnzi6N'
EMAIL_FROM = "info+sandbox@ysc.org"
EMAIL_FROM_NAME = "YSC Test Sandbox"
EMAIL_CONTACT = "info+sandbox@ysc.org"
EMAIL_ADMIN = "admin+sandbox@ysc.org"
EMAIL_MEMBERSHIP = "membership+sandbox@ysc.org"
EMAIL_BOARD = "board+sandbox@ysc.org"
EMAIL_VOLUNTEER = "volunteer+sandbox@ysc.org"
EMAIL_TAHOE = "tahoe+sandbox@ysc.org"
EMAIL_CLEAR_LAKE = "clearlake+sandbox@ysc.org"

[http_service]
internal_port = 4000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[http_service.concurrency]
type = 'connections'
hard_limit = 1000
soft_limit = 1000

[[vm]]
size = 'shared-cpu-1x'
memory = 512
