# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy Sandbox
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app sandbox
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: fly deploy --dockerfile etc/docker/Dockerfile -a ysc-sandbox -c etc/fly/fly-sandbox.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
